# Generated by Django 4.1.7 on 2023-06-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=100)),
                ('password', models.CharField(default=None, max_length=100)),
                ('radio_field', models.CharField(choices=[('Employeer', 'Employeer'), ('Job seeker', 'Job seeker')], max_length=10)),
            ],
        ),
    ]
